# Generated by Django 4.0.5 on 2022-11-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.bids'),
        ),
    ]
